server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Збір логів для всіх мікросервісів за допомогою Docker Service labels
  - job_name: "microservices-logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Встановлення лейблу container з імені контейнера
      - source_labels: [__meta_docker_container_name]
        target_label: container
      # Встановлення лейблу image з Docker image
      - source_labels: [__meta_docker_image]
        target_label: image
      # Встановлення лейблу container_id з Docker контейнера ID
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      # Встановлення лейблу service з Docker Compose service (цей лейбл автоматично буде отримано з Docker Compose)
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      # Встановлення шляху до логів контейнера
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/${1}/*-json.log
